version: "3"

services:
  urbex-api:
    image: node:alpine
    ports:
      - "80:3000"
    volumes:
      - .:/home/node/api
    working_dir: /home/node/api
    command: npm run start
    depends_on:
      - urbex-database
    links:
      - urbex-database

  urbex-database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=urbex
      - MYSQL_USER=urbex
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - urbex-data:/var/lib/mysql

  urbex-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=urbex-database
      - PMA_USER=urbex
      - PMA_PASSWORD=root
    links:
      - urbex-database

volumes:
  urbex-data:
